[package]
name = "connect"
edition = "2018"
version = "1.0.0"
authors = ["Michael Richardson <mcr@sandelman.ca>"]
# build = "build.rs"

[dependencies]
futures = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
nix  = "0.19.0"
netlink-packet-route = { path = "/ssw/projects/pandora/connect/netlink/netlink-packet-route", version = "0.5" }
rtnetlink     = { path = "/ssw/projects/pandora/connect/netlink/rtnetlink",     version = "0.5" }
netlink-proto = { path = "/ssw/projects/pandora/connect/netlink/netlink-proto", version = "0.4" }
tokio = { version = "0.2.6", features = ["macros", "rt-core"] }

[dev-dependencies]


