#[allow(non_camel_case_types)]
pub enum whack_message_keys {
  WHACK_STATUS = 1,
  WHACK_SHUTDOWN = 2,
  WHACK_OPTIONS = 3,
  WHACK_CONNECTION = 4,
  WHACK_ROUTE = 5,
  WHACK_UNROUTE = 6,
  WHACK_INITIATE = 7,
  WHACK_INITIATE_OPPO = 8,
  WHACK_TERMINATE = 9,
  WHACK_ADD_KEY = 10,
  WHACK_DELETE = 11,
  WHACK_LISTEN = 13,
  WHACK_UNLISTEN = 14,
  WHACK_LIST = 15,
  WHACK_PURGE_OCSP = 16,
  WHACK_REREAD = 17,
  WHACK_MYID = 22,
  WHACK_DELETESTATE = 23,
  WHACK_CRASHPEER = 24,
  WHACK_ASYNC = 25,
  WHACK_NOOP = 99,
}

#[allow(non_camel_case_types)]
pub enum statusoptions_keys {
  WHACK_STAT_OPTIONS = 1,
  WHACK_STAT_ALGORITHMS = 2,
  WHACK_STAT_JSON = 3,
  WHACK_STAT_POLICY = 4,
  WHACK_STAT_STATES = 5,
}



